### ISSUE TITLE
gnome terminal and ctrl-shift v

### ISSUE THREAD

**Issue by rpietro** [leehblue/texpander#8]
Lee, great script, really like it, was tired of the inconsistency in autokey. the only issue i'm having is that it won't work on a gnome-terminal, likely because text is pasted with ctrl-shift v

i can obviously create bash aliases for stuff that goes on the terminal, but was wondering if there was some other work around.

thanks for creating texpander, really simple and helpful

**Comment by leehblue** [comment]
It all comes down to line #22 having a text match on the name of the terminal you are using. You just need to look at the name assigned to your terminal's process and the tweak that line so that it matches that process name. 

For example, you might try changing it to something like this that matches any process with "term" in the name:

`if [[ $proc_name =~ (term|terminator) ]]`

**Comment by rpietro** [comment]
Lee, thanks. I have the following process on htop:

> /usr/lib/gnome-terminal/gnome-terminal-server

I tried gnome-terminal, gnome-terminal-server, tried escaping the hyphen such as in "gnome\-terminal" and none of these worked. I also tried it on terminator, but it doesn't work either.

I then tried to open a terminal without tmux (I had it set to open as a default), and it also didn't work on both gnome-terminal and terminator.

Any other thoughts? Thanks

**Comment by rpietro** [comment]
Lee, I think I found the solution. The issue was with tmux since it won't take ctrl-v as a way of pasting from the clipboard. That got solved with a script from: https://grota.github.io/blog/2012/05/08/tmux-clipboard-integration/

To get texpander to work I now use: ctrl-b *before* I expand the text from texpander. Works like a charm
